# -*- coding: utf-8 -*-
"""llamaindex_rag.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3pSGU9affDFOmujMCOY3DDyAQIibQpz
"""

!huggingface-cli login

!pip install -U -q pypdf

!pip install -U -q transformers einops accelerate bitsandbytes

!pip install -U -q sentence_transformers

!pip install -U -q llama-index-embeddings-huggingface
!pip install -U -q llama-index-llms-huggingface

!pip install -U -q llama-index

from llama_index.core import VectorStoreIndex, SimpleDirectoryReader, ServiceContext
from llama_index.embeddings.huggingface import HuggingFaceEmbedding
from llama_index.llms.huggingface import HuggingFaceLLM
from llama_index.core import PromptTemplate

documents = SimpleDirectoryReader("/content/data").load_data()

system_prompt = """
You are a Q&A assistant acting on behalf of a college.
Your goal is to answer questions as accurately
as possible based on the instructions adn context provided.
"""

query_wrapper_prompt = PromptTemplate("<|USER|>{query_str}<|ASSISTANT|>")

import torch

llm = HuggingFaceLLM(
    context_window=4096,
    max_new_tokens=256,
    generate_kwargs={"temperature": 0.01, "do_sample": True},
    system_prompt=system_prompt,
    query_wrapper_prompt=query_wrapper_prompt,
    tokenizer_name="meta-llama/Llama-2-7b-chat-hf",
    model_name="meta-llama/Llama-2-7b-chat-hf",
    device_map="auto",
    model_kwargs={"torch_dtype": torch.float16 , "load_in_8bit":True}
)

embed_model = HuggingFaceEmbedding(model_name='sentence-transformers/all-mpnet-base-v2')

service_context = ServiceContext.from_defaults(
    chunk_size=1024,
    llm=llm,
    embed_model=embed_model
)

index = VectorStoreIndex.from_documents(documents, service_context=service_context)

query_engine = index.as_query_engine()

response = query_engine.query('When is the holiday for Ramzan scheduled on?')
print(response)

response = query_engine.query('Why is the college following Saturday\'s timetable on February 21st, Wednesday?')
print(response)

response = query_engine.query('What is the assessment plan for the sixth semester students?')
print(response)

response = query_engine.query('What are FISACs?')
print(response)

response = query_engine.query('What is the current protocol for missing any one of the assesments?')
print(response)

